#!/bin/bash

function aptinstall() {
    envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
    aptopt="-qq"
    filter="grep  -Ev '^NEEDRESTART|^update|Reading'"
    sudo $envopt apt-get install $aptopt $@ | $filter
}