#!/bin/bash

function aptinstall() {
    envopt='NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive'
    aptopt='-qq'
    filter='^NEEDRESTART|^update|Reading'
    sudo $envopt apt-get install $aptopt $@ | grep -Ev $filter
}