#!/bin/bash

envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
aptopt="-qq"

sudo $envopt apt-get install $aptopt mc
mkdir -p ~/.config/mc
ln -sf ~/GitHub/config/mc/ini ~/.config/mc/ini
ln -sf ~/GitHub/config/mc/panels.ini ~/.config/mc/panels.ini