#!/bin/bash

envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
aptopt="-qq"

echo "Installing PHP..."
sudo add-apt-repository -y ppa:ondrej/php
sudo apt update > /dev/null
sudo $envopt apt-get install $aptopt php8.2 > /dev/null
sudo $envopt apt-get install $aptopt php8.2-{bcmath,fpm,xml,mysql,zip,intl,ldap,gd} > /dev/null
sudo $envopt apt-get install $aptopt php8.2-{cli,bz2,curl,mbstring,opcache,soap,cgi} > /dev/null
