#!/bin/bash

github="https://raw.githubusercontent.com/barabasz/bin/main/linux/install"

# Load functions
source /dev/stdin <<< "$(curl -fsSL $github/load-functions)"

# Install core
gitscript $github/install-core

# set temporary path
gitsource $github/set-path

# core tools & apps
printhead 'Installing essential packages...'
install-essentials

# Pyhon & pip
printhead 'Installing Python...'
install-python

# PHP
printhead 'Installing PHP...'
install-php
printhead 'Installing PHP Composer...'
install-composer

# Lua
printhead 'Installing Lua...'
install-lua

# mc (Midnight Commander)
printhead 'Installing mc...'
install-mc

# nvim (neovim)
printhead 'Installing nvim...'
install-nvim
