#!/bin/bash

# install zsh
aptinstall zsh

# set default shell
# chsh -s $(which zsh)
sudo chsh -s $(which zsh) $(whoami)

# make temporary .zshrc
echo 'export PATH=$HOME/bin:$HOME/bin/install:$HOME/binc:$PATH' >> ~/.zshrc
echo 'export PS1="[%{%F{cyan}%}%n%{%f%}@%{%F{green}%}%m:%{%F{yellow}%}%~%{%f%}%]]$ "' >>  ~/.zshrc
