#!/bin/bash

# Update, upgrade & cleanup
sudo NEEDRESTART_MODE=a apt update && sudo apt -y upgrade
sudo apt autoremove

# Certs & security
sudo NEEDRESTART_MODE=a apt install -y openssh-server gnupg2 ca-certificates acl

# Basic tools
sudo NEEDRESTART_MODE=a apt install -y net-tools lsb-release apt-transport-https software-properties-common

# Basic languages
sudo NEEDRESTART_MODE=a apt -y install build-essential cmake ninja-build

