#!/bin/bash

envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"

sudo apt update
sudo $envopt apt -qq upgrade
sudo apt dist-upgrade
sudo apt -y clean
sudo apt -y autoclean
sudo apt -y autoremove
sudo sync
