#!/bin/bash

# Certs & security
aptinstall openssh-server gnupg2 ca-certificates acl

# Software info
aptinstall lsb-release software-properties-common

# Basic tools
aptinstall net-tools apt-transport-https

# Basic languages
aptinstall build-essential cmake ninja-build
