#!/bin/bash

sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update > /dev/null
aptinstall php8.2
aptinstall php8.2-{bcmath,fpm,xml,mysql,zip,intl,ldap,gd,cli,bz2,curl,mbstring,opcache,soap,cgi}
