#!/bin/bash

github="https://raw.githubusercontent.com/barabasz/bin/main/linux/install"

# Install core
/bin/bash -c "$(curl -fsSL $github/install-core)"

# core tools & apps
echo 'Installing essential packages...'
install-essentials

# Pyhon & pip
echo 'Installing Python...'
install-python

# PHP
echo 'Installing PHP...'
install-php
echo 'Installing PHP Composer...'
install-composer

# Lua
echo 'Installing Lua...'
install-lua

# mc (Midnight Commander)
echo 'Installing mc...'
install-mc

# nvim (neovim)
echo 'Installing nvim...'
install-nvim
