#!/bin/sh

github="https://raw.githubusercontent.com/barabasz/bin/main/linux/install"

# Git, gh
/bin/bash -c "$(curl -fsSL $github/install-git)"

# clone setup repositories
/bin/bash -c "$(curl -fsSL $github/install-repos)"

# zsh & omz
/bin/bash -c "$(curl -fsSL $github/install-zsh)"
exec zsh
install-omz

# remove snap
remove-snap

# minimize login info
fix-login-info

# set locale
set-locale

# core tools & apps
install-essentials

# Pyhon & pip
install-python

# PHP
install-php
install-composer

# Lua
install-lua

# mc (Midnight Commander)
install-mc

# nvim (neovim)
install-nvim
