#!/bin/bash

# load aptinstall
source /dev/stdin <<< "$(curl -fsSL https://raw.githubusercontent.com/barabasz/bin/main/linux/functions/aptinstall)"

# install zsh
aptinstall zsh

# set default shell
chsh -s $(which zsh)

# make temporary .zshrc
echo 'export PATH=$HOME/bin:$HOME/bin/install:$HOME/binc:$PATH' >> ~/.zshrc
echo 'export PS1="[%{%F{cyan}%}%n%{%f%}@%{%F{green}%}%m:%{%F{yellow}%}%~%{%f%}%]]$ "' >>  ~/.zshrc
