#!/bin/bash

aptinstall fuse
mkdir -p ~/Downloads && cd $_
curl -fsSLO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage 
sudo mv nvim.appimage /usr/local/bin/nvim
sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/nvim 1000

# pynvim
dist=$(cat /etc/os-release | grep -m 1 -o "Debian")
if [[ "$dist" == "Debian" ]]; then
    pip install pynvim --break-system-packages
else
    pip install pynvim
fi

# Configuration files
mkdir -p ~/.config/nvim
ln -sf ~/GitHub/config/nvim/init.vim ~/.config/nvim

# Plugin manager
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Load plugins
nvim --headless +'PlugInstall' +qa

