#!/bin/bash

github="https://raw.githubusercontent.com/barabasz/bin/main/linux/install"
sudo apt-get install curl > /dev/null

# load functions
printf "\n\e[33m\e[1mLoading functions...\033[0m\n"
source /dev/stdin <<< "$(curl -fsSL $github/load-functions)"
echo 'OK'

# Update and upgrade
printhead 'Updating system...'
gitscript $github/install-updates

# Git
printhead 'Installing git...'
gitscript $github/install-git
echo 'OK'

# clone setup repositories
printhead 'Cloning setup repositories...'
gitscript $github/install-repos

# set locale
printhead 'Setting locale...'
gitsource $github/set-locale

# set temporary path
printhead 'Setting path...'
gitsource $github/set-path
echo 'OK'

# minimize login info
printhead 'Minimizing login info...'
fix-login-info
echo 'OK'

# remove snap
printhead 'Removing snap...'
remove-snap

# zsh
printhead 'Installing zsh...'
install-zsh

# omz
printhead 'Installing oh-my-zsh...'
install-omz
