#!/bin/bash

envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
aptopt="-qq"

sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo $envopt apt-get install $aptopt php8.2
sudo $envopt apt-get install $aptopt php8.2-{bcmath,fpm,xml,mysql,zip,intl,ldap,gd}
sudo $envopt apt-get install $aptopt php8.2-{cli,bz2,curl,mbstring,opcache,soap,cgi}
