#!/bin/bash

envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
aptopt="-qq"

sudo apt-get update
sudo $envopt apt-get $aptopt upgrade
sudo $envopt apt-get $aptopt dist-upgrade

sudo apt-get $aptopt clean
sudo apt-get $aptopt autoclean
sudo apt-get $aptopt autoremove
sudo sync
