#!/bin/zsh

# core tools & apps
printhead 'Installing essential packages...'
install-essentials

# Pyhon & pip
printhead 'Installing Python...'
install-python

# PHP
printhead 'Installing PHP...'
install-php
printhead 'Installing PHP Composer...'
install-composer

# Lua
printhead 'Installing Lua...'
install-lua

# mc (Midnight Commander)
printhead 'Installing mc...'
install-mc

# nvim (neovim)
printhead 'Installing nvim...'
install-nvim
