#!/bin/bash

github="https://raw.githubusercontent.com/barabasz/bin/main/linux/install"

#### load printinf

# Update and upgrade
printhead 'Updating system...'
gitscript $github/install-updates

# Git, gh
printinf 'Installing git...'
gitscript $github/install-git

# clone setup repositories
printinf 'Cloning setup repositories...'
gitscript $github/install-repos

# set temporary path
gitsource $github/install-path

# set locale
printinf 'Setting locale...'
install-locale

# minimize login info
printinf 'Minimizing login info...'
fix-login-info

# remove snap
printinf 'Removing snap...'
remove-snap

# zsh
printinf 'Installing zsh...'
install-zsh

# omz
printinf 'Installing oh-my-zsh...'
install-omz
