#!/bin/bash

gitpath=https://raw.githubusercontent.com/barabasz/bin/main/common/functions/

source /dev/stdin <<< "$(curl -fsSL $gitpath/printhead)"
source /dev/stdin <<< "$(curl -fsSL $gitpath/gitscript)"
source /dev/stdin <<< "$(curl -fsSL $gitpath/gitsource)"
source /dev/stdin <<< "$(curl -fsSL $gitpath/aptinstall)"

