#!/bin/zsh

# Show All Extensions
defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "true"

# Disable "Changing file extension warning"
defaults write com.apple.finder "FXEnableExtensionChangeWarning" -bool "false"

# Keep folders on top 
defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

# Default column view
defaults write com.apple.finder "FXPreferredViewStyle" -string "clmv"

# Show path bar
defaults write com.apple.finder "ShowPathbar" -bool "true"

# Restart Finder
killall Finder
