#!/bin/zsh

# read su password
sudo printf ''

# core tools & apps
printhead 'Installing essential packages...'
install-essentials
echo 'Done.'

# cmake  - Cross-platform make
printhead 'Installing cmake...'
install-cmake

# gcc  - GNU compiler collection
printhead 'Installing gcc...'
install-gcc

# Pyhon & pip
printhead 'Installing Python...'
install-python

# PHP
printhead 'Installing PHP...'
install-php
printhead 'Installing PHP Composer...'
install-composer

# Lua
printhead 'Installing Lua...'
install-lua

printhead 'Installation completed.'