#!/bin/bash

# load functions
github="https://raw.githubusercontent.com/barabasz/bin/main/linux/install"
source /dev/stdin <<< "$(curl -fsSL $github/load-functions)"

if [[ "$(osname)" == "macos" ]]; then
    xcode-select --install
else
    aptinstall git
fi

