#!/bin/bash

# load functions
github="https://raw.githubusercontent.com/barabasz/bin/main/common/install"
source /dev/stdin <<< "$(curl -fsSL $github/load-functions)"

if [[ "$(isinstalled git)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        xcode-select --install
    else
        aptinstall git
    fi
else
    git --version
fi
