#!/bin/bash

# load functions
source ~/.zsh_functions
source ~/.zsh_locale

if [[ "$(isinstalled gh)" == "no" ]]; then
    brew install -q gh
else
    gh --version
fi

if [[ "$(gh auth status | grep -o 'Logged')" == "Logged" ]]; then
    gh auth status | grep 'Logged'
else
    gh auth login
fi
