#!/bin/bash

# yazi
# terminal file manager written in Rust
# https://github.com/sxyazi/yazi

appname=yazi

if [[ "$(isinstalled $appname)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install $appname --HEAD
    else
        aptinstall $appname
    fi
else 
    $appname --version
fi

if [[ -d $CONFDIR/$appname || -h $CONFDIR/$appname ]]; then
    rm -r $CONFDIR/$appname
    ln -sF $GHCONFDIR/$appname $CONFDIR/$appname
fi

if [[ ! -f $CONFDIR/$appname ]]; then
    mkdir -p $CONFDIR
    
fi