#!/bin/bash

# load functions
echo 'Loading install environment and functions...'
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

appname="GitHub CLI"
cliname=gh
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi

if [[ "$(gh auth status | grep -o 'Logged')" == "Logged" ]]; then
    gh auth status | grep 'Logged'
else
    gh auth login
fi
