#!/bin/bash

if [[ "$(isinstalled gh)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q gh
    else
        aptinstall gh
    fi
else
    gh --version
fi

if [[ "$(gh auth status | grep -o 'Logged')" == "Logged" ]]; then
    gh auth status | grep 'Logged'
else
    gh auth login
fi
