#!/bin/zsh

# ffmpeg
# Play, record, convert, and stream audio and video
# https://ffmpeg.org/

if [[ "$(isinstalled ffmpeg)" == "no" ]]; then
    brew install -q ffmpeg
else
    ffmpeg -version | grep "ffmpeg version"
fi