#!/bin/bash

# load functions
zshpath=https://raw.githubusercontent.com/barabasz/config/main/zsh/
source /dev/stdin <<< "$(curl -fsSL $zshpath/.zsh_functions)"

# Common scripts
ln -sf ~/GitHub/bin/common ~/binc

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    ln -sf ~/GitHub/bin/macos ~/bin
else
    ln -sf ~/GitHub/bin/linux ~/bin
fi

# Library
ln -sf ~/GitHub/bin/lib ~/

# ZSH
ln -sf ~/GitHub/config/zsh/.zprofile ~/
ln -sf ~/GitHub/config/zsh/.zshrc ~/
ln -sf ~/GitHub/config/zsh/.zsh_aliases ~/
ln -sf ~/GitHub/config/zsh/.zsh_functions ~/
ln -sf ~/GitHub/config/zsh/.zsh_locale ~/
