#!/bin/bash

if [[ "$(isinstalled mc)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q midnight-commander
    else
        aptinstall mc
    fi
else 
    mc --version | grep 'Midnight Commander'
fi

mkdir -p ~/.config/mc
ln -sf ~/GitHub/config/mc/ini ~/.config/mc/ini
ln -sf ~/GitHub/config/mc/panels.ini ~/.config/mc/panels.ini
