#!/bin/zsh

# eza
# modern alternative for the ls
# https://github.com/eza-community/eza

appname=eza
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi