#!/bin/bash

# Brew core packages

# load functions
echo 'Loading install environment and functions...'
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

if [[ "$(isinstalled brew)" == "yes" ]]; then
    brew install -q gmp isl mpfr libmpc lz4 xz bzip2 zlib zstd binutils m4 pkgconf
else
    echo "Brew is not installed"
fi
