#!/bin/bash

# ca-certificates
# Mozilla CA certificate store
# https://curl.se/docs/caextract.html

if [[ "$(isinstalledbybrew ca-certificates)" == "no" ]]; then
    brew install -q ca-certificates
else
    brew list ca-certificates
fi
