#!/bin/bash

# load functions
zshpath=https://raw.githubusercontent.com/barabasz/config/main/zsh/
source /dev/stdin <<< "$(curl -fsSL $zshpath/.zshenv)"
source /dev/stdin <<< "$(curl -fsSL $zshpath/.zsh_functions)"

# Common scripts
ln -sf $GHBINDIR/common $HOME/bin

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    ln -sf $GHBINDIR/macos ~/bin
else
    ln -sf $GHBINDIR/linux ~/bin
fi

# Library
ln -sF $GHBINDIR/lib $HOME/lib

# ZSH
ln -sF $GHCONFDIR/zsh $CONFDIR/zsh2