#!/bin/zsh

# Karabiner-Elements
# A powerful and stable keyboard customizer for macOS
# https://karabiner-elements.pqrs.org

appname='Karabiner-Elements'
cliname=karabiner_cli
dirname=karabiner
pkgname=karabiner-elements

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install --cask $pkgname
else
    echo "$appname $($cliname --version)"
fi

if [[ -d $CONFDIR/$appname ]]; then
    rm -r $CONFDIR/$appname
    ln -sfF $GHCONFDIR/$appname $CONFDIR/$appname
fi