#!/bin/zsh

if [[ "$(echo $ZSH | grep -o 'oh-my-zsh')" != "oh-my-zsh" ]]; then
    omzinstall=https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    sh -c "$(curl -fsSL $omzinstall)" "" --unattended
    rm -f ~/.zshrc.pre-oh-my-zsh
    rm -f ~/.shell.pre-oh-my-zsh
fi

ln -sf ~/GitHub/config/zsh/.zprofile ~/
ln -sf ~/GitHub/config/zsh/.zshrc ~/
ln -sf ~/GitHub/config/zsh/.p10k.zsh ~/

# Powerlevel10k theme
powerlevel10k=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
if [[ ! -d $powerlevel10k ]]; then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $powerlevel10k
fi

# Fish-like fast/unobtrusive autosuggestions
autosuggestions=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
if [[ ! -d $autosuggestions ]]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git $autosuggestions
fi

# Fish shell-like syntax highlighting
syntaxhighlighting=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
if [[ ! -d $syntaxhighlighting ]]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $syntaxhighlighting
fi

source ~/.zshrc