#!/bin/bash

# THIS SCRIPT IS INTENTIONALLY WRITTEN IN BASH

# load functions
echo 'Loading install environment and functions...'
functions="https://raw.githubusercontent.com/barabasz/config/main/zsh/.zsh_functions"
source <(curl -fsSL $functions)

if [[ "$(osname)" == "ubuntu" ]]; then
    sudo apt install -yq locales > /dev/null 2>&1
    sudo locale-gen en_US.UTF-8
    sudo locale-gen pl_PL.UTF-8
    sudo update-locale
    echo "Locales updated."
else
    echo "Unsupported OS: $(osname)"
    exit 1
fi
