#!/bin/bash

# symbolic links
ln -sf ~/GitHub/config/zsh/.zprofile ~/
ln -sf ~/GitHub/config/zsh/.zshrc ~/
ln -sf ~/GitHub/config/zsh/.zsh_aliases ~/
ln -sf ~/GitHub/config/zsh/.zsh_functions ~/

# load aliases & functions
source ~/.zsh_aliases
source ~/.zsh_functions

# fallback for bash's shopt
if [[ ! "$(osname)" == "macos" ]]; then
    sudo ln -sf ~/GitHub/bin/common/shopt /usr/bin/shopt
fi

# install zsh
if [[ "$(isinstalled zsh)" == "no" ]]; then
    if [[ ! "$(osname)" == "macos" ]]; then
        aptinstall zsh
    fi
else
    $(which zsh) --version
fi

# set default shell
if [[ "$(echo $SHELL | grep -o 'zsh')" != "zsh" ]]; then
    sudo chsh -s $(which zsh) $(whoami)
fi
