#!/bin/bash

# load functions
zshpath=https://raw.githubusercontent.com/barabasz/config/main/zsh/
source /dev/stdin <<< "$(curl -fsSL $zshpath/.zsh_functions)"

mkdir -p ~/GitHub && cd $_

if [[ ! -d ~/GitHub/bin ]]; then
    git clone https://github.com/barabasz/bin.git
else
    echo '"bin" repo already cloned.'
fi

if [[ ! -d ~/GitHub/config ]]; then
    git clone https://github.com/barabasz/config.git
else
    echo '"config" repo already cloned.'
fi

if [[ ! -d ~/GitHub/resources ]]; then
    git clone https://github.com/barabasz/resources.git
else
    echo '"resources" repo already cloned.'
fi

if [[ ! -d ~/GitHub/cheatsheets ]]; then
    git clone https://github.com/barabasz/cheatsheets.git
else
    echo '"cheatsheets" repo already cloned.'
fi

if [[ ! -d ~/GitHub/urlinfo ]]; then
    git clone https://github.com/barabasz/urlinfo.git
else
    echo '"urlinfo" repo already cloned.'
fi

# Common scripts
ln -sf ~/GitHub/bin/common ~/binc

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    ln -sf ~/GitHub/bin/macos ~/bin
else
    ln -sf ~/GitHub/bin/linux ~/bin
fi

# Library
ln -sf ~/GitHub/bin/lib ~/

# Core symlinks
ln -sf ~/GitHub/config/zsh/.zprofile ~/
ln -sf ~/GitHub/config/zsh/.zshrc ~/
ln -sf ~/GitHub/config/zsh/.zsh_aliases ~/
ln -sf ~/GitHub/config/zsh/.zsh_functions ~/
ln -sf ~/GitHub/config/zsh/.zsh_locale ~/
