#!/bin/zsh

# yt-dlp
# YouTube video downloader
# https://github.com/yt-dlp/yt-dlp

appname=yt-dlp
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi
