#!/bin/bash

# nnn
# Tiny, lightning fast, feature-packed file manager
# https://github.com/jarun/nnn

appname=nnn
cliname=$appname
dirname=$appname
pkgname=$appname
vercmmd="-V"

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q $pkgname
    else
        aptinstall $cliname
    fi
else
    verinf $cliname "$appname" $vercmmd
fi

makeconfln $dirname
# Install plugins
sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
