#!/bin/bash

# mc (Midnight Commander)
# feature rich full-screen text mode visual file manager
# https://midnight-commander.org/

appname='Midnight Commander'
cliname=mc
dirname=$cliname
pkgname=midnight-commander

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q midnight-commander
    else
        aptinstall $cliname
    fi
else
    verinf $appname $cliname
fi

makeconfln $dirname