#!/bin/bash

if [[ "$(isinstalled lua)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q lua luarocks luv luajit
    else
        aptinstall lua5.4
    fi
else
    lua -v
fi
