#!/bin/zsh

# Karabiner-Elements
# A powerful and stable keyboard customizer for macOS
# https://karabiner-elements.pqrs.org

if [[ "$(isinstalled karabiner_cli)" == "no" ]]; then
    brew install --cask karabiner-elements
else
    echo "Karabiner-Elements $(karabiner_cli --version)"
fi

mkdir -p ~/.config/karabiner
ln -sf ~/GitHub/config/karabiner/karabiner.json ~/.config/karabiner/karabiner.json