#!/bin/bash

# symbolic links
ln -sf ~/GitHub/config/zsh/.zprofile ~/
ln -sf ~/GitHub/config/zsh/.zshrc ~/
ln -sf ~/GitHub/config/zsh/.zsh_aliases ~/
ln -sf ~/GitHub/config/zsh/.zsh_functions ~/
ln -sf ~/GitHub/config/zsh/.zsh_locale ~/

# load aliases & functions
source ~/.zsh_aliases
source ~/.zsh_functions
source ~/.zsh_locale

# fallback for bash's shopt
if [[ ! "$(osname)" == "macos" ]]; then
    sudo ln -sf ~/GitHub/bin/common/shopt /usr/bin/shopt
fi

# install zsh
if [[ "$(isinstalled zsh)" == "no" ]]; then
    if [[ ! "$(osname)" == "macos" ]]; then
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        aptinstall zsh
    fi
else
    $(which zsh) --version
fi

# set default shell
if [[ "$(echo $SHELL | grep -o 'zsh')" != "zsh" ]]; then
    sudo sed -i 's/required/sufficient/g' /etc/pam.d/chsh
    sudo chsh -s $(which zsh) $(whoami)
    sudo sed -i 's/sufficient/required/g' /etc/pam.d/chsh
fi
