#!/bin/zsh

# read su password
sudo printf ''

# gh
printhead 'Installing GitHub CLI...'
install-gh

# core tools & apps
printhead 'Installing essential packages...'
install-essentials
echo 'Done.'

# Pyhon & pip
printhead 'Installing Python...'
install-python

# PHP
printhead 'Installing PHP...'
install-php
printhead 'Installing PHP Composer...'
install-composer

# Lua
printhead 'Installing Lua...'
install-lua

# mc (Midnight Commander)
printhead 'Installing mc...'
install-mc

# nvim (neovim)
printhead 'Installing nvim...'
install-nvim

# navi
printhead 'Installing navi...'
install-navi

printhead 'Installation completed.'