#!/bin/bash

# load functions
zshpath=https://raw.githubusercontent.com/barabasz/config/main/zsh/
source /dev/stdin <<< "$(curl -fsSL $zshpath/.zsh_functions)"

mkdir -p ~/GitHub && cd $_

if [[ ! -d ~/GitHub/bin ]]; then
    git clone https://github.com/barabasz/bin.git
else
    echo '"bin" repo already cloned.'
fi

if [[ ! -d ~/GitHub/config ]]; then
    git clone https://github.com/barabasz/config.git
else
    echo '"config" repo already cloned.'
fi

# Common scripts
ln -sf ~/GitHub/bin/common ~/binc

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    ln -sf ~/GitHub/bin/macos ~/bin
else
    ln -sf ~/GitHub/bin/linux ~/bin
fi