#!/bin/bash

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat

appname=bat
cliname=bat
dirname=$cliname
pkgname=bat

if [[ "$(isinstalled $appname)" == "no" ]]; then
    brew install -q $appname
else
    verinf $appname $cliname
fi

makeconfln $dirname