#!/bin/zsh

brews='ca-certificates bzip2 m4 pkg-config gpatch lz4 xz bison'
if [[ "$(osname)" != "macos" ]]; then brews="$brews zlib"; fi
brews="$brews openssl@3 gmp ncurses zstd binutils"
brews="$brews isl mpfr cmake"
brews="$brews libmpc"
brews="$brews gcc"
brews="$brews icu4c readline unibilium libuv libvterm luajit luv"
brews="$brews msgpack tree-sitter fzf pcre2 libxcrypt expat"
if [[ "$(osname)" != "macos" ]]; then brews="$brews libedit"; fi
brews="$brews libtermkey krb5 dbus"
if [[ "$(osname)" != "macos" ]]; then brews="$brews libxml2"; fi
brews="$brews gettext"
if [[ "$(osname)" != "macos" ]]; then brews="$brews libtirpc libnsl"; fi
brews="$brews tree sevenzip"
brew install -q $brews

if [[ "$(osname)" == "macos" ]]; then
    brew install -q htop
else
    aptinstall htop net-tools ca-certificates acl lsb-release software-properties-common
    #build-essential gcc ninja-build
fi
