#!/bin/zsh

# read su password
sudo printf ''

# Pyhon & pip
printhead 'Installing Python...'
install-python

# PHP
printhead 'Installing PHP...'
install-php
printhead 'Installing PHP Composer...'
install-composer

# Lua
printhead 'Installing Lua...'
install-lua

printhead 'Installation completed.'