#!/bin/bash

# fzf
# Command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf

appname=fzf
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi
