#!/bin/zsh

if [[ "$(osname)" == "macos" ]]; then
    brew install -q ca-certificates fzf
else
    aptinstall net-tools ca-certificates fzf acl lsb-release software-properties-common build-essential gcc cmake ninja-build
fi

