#!/bin/bash

# fzf
# Command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf

if [[ "$(isinstalled fzf)" == "no" ]]; then
    brew install -q fzf
else
    echo "fzf $(fzf --version)"
fi
