#!/bin/bash

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat

appname=bat
cliname=bat
dirname=bat
pkgname=bat


if [[ "$(isinstalled $appname)" == "no" ]]; then
    brew install -q $appname
else
    echo "$appname $($cliname --version | grep -Eo '[0-9]\.[0-9]+') is already installed"
fi

if [[ -d $CONFDIR/$dirname || -h $CONFDIR/$dirname ]]; then
    rm -r $CONFDIR/$dirname
    ln -sF $GHCONFDIR/$dirname $CONFDIR/$dirname
fi