#!/bin/zsh

# espanso
# A Privacy-first, Cross-platform Text Expander
# https://espanso.org

 [[ ! -z $ZSH_FUNCTIONS_LOADED ]] && [[ -f $ZFNFILE ]] && source $ZFNFILE

if [[ "$(isinstalled espanso)" == "no" ]]; then
    brew install espanso
else
    espanso --version
fi

lnf $GHCONFPRIVDIR/espanso ~/Library/Application\ Support/espanso
