#!/bin/bash

# load functions
echo 'Loading install environment and functions...'
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

appname=git
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        xcode-select --install
    else
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        aptinstall $pkgname
    fi
fi

if [[ -z "$(git config --global user.email)" ]]; then
    git config --global user.email "abarabasz@gmail.com"
    git config --global user.name "Andrzej Barabasz"
    git config --global core.pager bat
    git config --global core.editor code
fi

verinf $cliname "$appname"