#!/bin/zsh

# read su password
sudo printf ''

# gh
printhead 'Installing GitHub CLI...'
install-gh

# mc (Midnight Commander)
# feature rich full-screen text mode visual file manager
# https://midnight-commander.org/
printhead 'Installing mc...'
install-mc

# nnn
# Tiny, lightning fast, feature-packed file manager
# https://github.com/jarun/nnn
printhead 'Installing nnn...'
install-nnn

# fd
# fd is a program to find entries in your filesystem
# https://github.com/sharkdp/fd
printhead 'Installing fd...'
install-fd

# fzf
# Command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf
printhead 'Installing fzf...'
install-fzf

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat
printhead 'Installing bat...'
install-bat

# htop
# Improved top (interactive process viewer)
# https://htop.dev/
printhead 'Installing htop...'
install-htop

# nvim (neovim)
# hyperextensible Vim-based text editor
# https://neovim.io/
printhead 'Installing nvim...'
install-nvim

# navi
# Interactive cheatsheet tool for the command-line
# https://github.com/denisidoro/navi
printhead 'Installing navi...'
install-navi

# wget
# Internet file retriever
# https://www.gnu.org/software/wget/
printhead 'Installing wget...'
install-wget

# The Fuck
# Programmatically correct mistyped console commands
# https://github.com/nvbn/thefuck
printhead 'Installing thefuck...'
install-thefuck

# Lynx
# console web browser
# https://www.lynxcloud.app/
printhead 'Installing lynx...'
install-lynx

# calc
# C-style arbitrary precision calculator with custom functions
# http://www.isthe.com/chongo/tech/comp/calc/
printhead 'Installing calc...'
install-calc

# zzz
# put mac to sleep
# https://github.com/Orc/Zzz
if [[ "$(osname)" == "macos" ]]; then
    printhead 'Installing zzz...'
    install-zzz
fi

printinfo 'Shell apps installation completed.'
