#!/bin/bash

github="https://raw.githubusercontent.com/barabasz/bin/main/common/install"
sudo echo > /dev/null

# load functions
zshpath=https://raw.githubusercontent.com/barabasz/config/main/zsh/
source /dev/stdin <<< "$(curl -fsSL $zshpath/.zsh_functions)"
echo 'OK'

# Update and upgrade
if [[ ! "$(osname)" == "macos" ]]; then
    printhead 'Updating system...'
    extscript $(echo $github | sed 's/\/install//')/update
fi

# Git
printhead 'Installing git...'
extscript $github/install-git

# clone setup repositories
printhead 'Cloning setup repositories...'
extscript $github/install-repos

# brew
printhead 'Installing brew...'
extscript $github/install-brew

# set locale
if [[ "$(osname)" == "ubuntu" ]]; then
    printhead 'Setting locale...'
    extsource $(echo $github | sed 's/common\/install/linux/')/set-locale
fi

# set temporary path
export PATH=$HOME/bin:$HOME/bin/install:$HOME/binc:$HOME/binc/install:$HOME/binc/test:/usr/local/bin:$PATH

# minimize login info
if [[ ! "$(osname)" == "macos" ]]; then
    printhead 'Minimizing login info...'
    fix-login-info
    echo 'OK'
fi

# remove snap
if [[ "$(osname)" == "ubuntu" ]]; then
    printhead 'Removing snap...'
    remove-snap
fi

# zsh
if [[ ! "$(osname)" == "macos" ]]; then
    printhead 'Installing zsh...'
    install-zsh
fi

# omz
printhead 'Installing oh-my-zsh...'
install-omz

printhead 'Core installation completed.'
