#!/bin/bash

# load functions
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_EMOJI=1

if [[ "$(isinstalled brew)" == "no" ]]; then
    # Ubuntu/Debian fix
    if [[ "$(osname)" != "macos" ]]; then
        sudo mkdir -p /home/linuxbrew/
        sudo chmod 755 /home/linuxbrew/
    fi

    # Brew (unattended installation)
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Execute shellenv
    if [[ -f /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    fi

    # Disable analytics
    brew analytics off
else
    brew --version
fi




