#!/bin/zsh

# http://jafrog.com/2013/11/23/colors-in-terminal.html
# https://gist.github.com/JBlond/2fea43a3049b38287e5e9cefc87b2124

# To list all colors available in 256 color mode with their codes run
# 256-color mode — foreground: ESC[38;5;#m   background: ESC[48;5;#m
# for code in {0..255}
#     do echo -e "\e[38;5;${code}m"'\\e[38;5;'"$code"m"\e[0m"
# done

red='\e[31m'
green='\e[32m'
yellow='\e[33m'
blue='\e[34m'
magenta='\e[35m'
cyan='\e[36m'
gray='\e[38;5;238m'

bg_red='\e[41m'
bg_green='\e[42m'
bg_yellow='\e[43m'
bg_blue='\e[44m'
bg_magenta='\e[45m'
bg_cyan='\e[46m'

temp_bold='\e[1m'
temp_underline='\e[4m'

clear='\033[0m'