#!/bin/zsh

# load variables and functions
zshload="$ZDOTDIR/.zsh_load"; pref="\e[1;91m"; suff="\e[0m"
loaderr="${pref}Error loading $zshload: file not found.${suff}"
[[ -f $zshload ]] && source $zshload || { echo -e $loaderr; return 1; }

printhead "Pushing all repositories to the remote."

for repo in $(git-repos)
do
    printhead $(basename $repo)
    cd $repo
    printc $(git remote get-url origin)
    git add --all
    git commit -m "update"
    git push
done


