#!/bin/zsh

# load variables and functions
source $ZDOTDIR/.zsh_load

echo "🖥️ 👉 ☁️ ${redb}Pushing all repositories to the remote.${reset}"

for repo in $(git-repos)
do
    printhead $(basename $repo)
    cd $repo
    echo "${cyan}$(git remote get-url origin)${reset}"
    git add --all
    git commit -m "update"
    git push
done


