#!/bin/zsh

# load variables and functions
source $ZDOTDIR/.zsh_load
source $LIBDIR/prompt_continue.sh

echo "${red}This will reset all repositories to the latest commit on the main branch.${reset}"
prompt_continue

for repo in $(git-repos)
do
    printhead $(basename $repo)
    cd $repo
    echo "${cyan}$(git remote get-url origin)${reset}"
    git fetch origin
    git checkout main
    git reset --hard origin/main
    git pull
done
