#!/bin/zsh

# load variables and functions
zshload="$ZDOTDIR/.zsh_load"; pref="\e[1;91m"; suff="\e[0m"
loaderr="${pref}Error loading $zshload: file not found.${suff}"
[[ -f $zshload ]] && source $zshload || { echo -e $loaderr; return 1; }

echo "  ${redb}Pushing all repositories to the remote.${reset}"

for repo in $(git-repos)
do
    printhead $(basename $repo)
    cd $repo
    echo "${cyan}$(git remote get-url origin)${reset}"
    git add --all
    git commit -m "update"
    git push
done


