#!/bin/zsh

# load variables and functions
zshload="$ZDOTDIR/.zsh_load"; pref="\e[1;91m"; suff="\e[0m"
loaderr="${pref}Error loading $zshload: file not found.${suff}"
[[ -f $zshload ]] && source $zshload || { echo -e $loaderr; return 1; }

source $LIBDIR/prompt_continue.sh

printe "\nThis will reset all repositories to the latest commit on the main branch."
prompt_continue
if [ $? -ne 0 ]; then
    return 1
fi

for repo in $(git-repos)
do
    printhead $(basename $repo)
    cd $repo
    echo "${cyan}$(git remote get-url origin)${reset}"
    #git fetch origin
    #git checkout main
    #git reset --hard origin/main
    #git pull
done
