#!/bin/zsh

# colors
g='\e[32m' y='\e[33m' c='\e[36m' r='\e[31m' x='\e[0m'

# list of git repositories from $GHDIR folder
repos=($GHDIR/*(/))

if (( ${#repos} == 0 )); then
    print "${r}No repositories found in $GHDIR.${x}"
    return 1
fi

print "Pulling ${#repos} repositories from the remote."

i=1
for repo in $repos; do
    print "\n$y$i/${#repos} $g${repo:t}$x"
    print "$c$(git -C $repo remote get-url origin)$x"
    git -C $repo pull --rebase 2>&1 | while read line; do
        if [[ $line == *error:* ]]; then
            print "$r$line$x"
        else
            print $line
        fi
    done
    ((i++))
done