#!/bin/zsh

printhead 'bin'
cd ~/GitHub/bin
git status

printhead 'config'
cd ~/GitHub/config
git status

printhead 'resources'
cd ~/GitHub/resources
git status

printhead 'scripts'
cd ~/GitHub/scripts
git status
