#!/bin/zsh

setopt nullglob
local i=0
local fonts=(*.otf *.ttf .*.otf .*.ttf)
for file in $fonts; do
    if [[ -f "$file" ]]; then
        local g=$(ansi green) b=$(ansi purple) r=$(ansi reset) y=$(ansi yellow)
        local name=$(exiftool -fontname -S $file | sed 's/^[^:]*: //')
        if [[ $name = "" ]]; then
            name=$(exiftool $file | grep "Font Name" | head -1 | sed 's/^[^:]*: //')
        fi
        [[ $name = "" ]] && echo "No font name found for $file." && continue
        local filename="${file:t:r}"
        local extension="${file##*.}"
        echo "$b$file$r ${y}→$r $g$name.$extension"$r
        mv $file $name.$extension
        ((i++))
    else
        echo "No font files found in the current directory."
        break
    fi
done

echo "\n$i files renamed."

unsetopt nullglob
