#!/bin/bash

# THIS SCRIPT IS INTENTIONALLY WRITTEN IN BASH

echo "osname from update (before loading): $(osname)"

# load functions
loadfnurl="https://raw.githubusercontent.com/barabasz/bin/main/common/loadfn"
source <(curl -fsSL $loadfnurl)
#if command -v loadfn &> /dev/null; then loadfn
#else source <(curl -fsSL $loadfnurl); fi

echo "osname from update (after loading): $(osname)"

if [[ ! "$(osname)" == "macos" ]]; then
    envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
    aptopt="-qq"
    filter1='^Hit|^Get'
    filter2='^NEEDRESTART|^update|Reading'

    sudo apt-get update | grep -Ev $filter1
    sudo $envopt apt-get $aptopt upgrade | grep -Ev $filter2
    sudo $envopt apt-get $aptopt dist-upgrade

    sudo apt-get $aptopt clean
    sudo apt-get $aptopt autoclean
    sudo apt-get $aptopt autoremove
    sudo sync
fi

if [[ "$(isinstalled brew)" == "yes" ]]; then
    brew update --auto-update
    brew upgrade
    brew cleanup
fi

