#!/bin/zsh

set -euo pipefail
source ~/.zsh_functions
source ~/lib/log.sh
source ~/lib/ansi.sh

# log::header 'header'
# log::success 'succes'
# log::error 'error'
# log::warning 'warning'
# log::note 'note'

# ansi::example
echo "$(ansi $@)$@"
# echo "$@ ($#)\n"