#!/bin/zsh

# Oh My Posh
# A prompt theme engine for any shell
# https://ohmyposh.dev
# https://github.com/JanDeDobbeleer/oh-my-posh

# load variables and functions
zshload="$ZDOTDIR/.zsh_load"; pref="\e[1;91m"; suff="\e[0m"
loaderr="${pref}Error loading $zshload: file not found.${suff}"
[[ -f $zshload ]] && source $zshload || { echo -e $loaderr; return 1; }

appname='Oh My Posh'
cliname=oh-my-posh
dirname=omp
iscript='https://ohmyposh.dev/install.sh'

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    [[ ! -d ~/bin ]] && mkdir ~/bin
    curl -s $iscript | bash -s -- -d ~/bin
    verinfo $cliname "$appname"
fi

makeconfln $dirname

verinfo $cliname "$appname"

