#!/bin/zsh

# load functions
source ~/.zsh_functions

if [[ "$(echo $ZSH | grep -o 'oh-my-zsh')" != "oh-my-zsh" ]]; then
    omzinstall=https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    export ZSH="$CONFDIR/omz"
    sh -c "$(curl -fsSL $omzinstall)" "" --unattended
    rm -f ~/.zshrc.pre-oh-my-zsh
    rm -f ~/.shell.pre-oh-my-zsh
else
    source ~/.zshrc
    omz update
    echo "Oh My Zsh version: $(omz version)"
fi

# Fish-like fast/unobtrusive autosuggestions
autosuggestions=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
if [[ ! -d $autosuggestions ]]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git $autosuggestions
fi

# Fish shell-like syntax highlighting
syntaxhighlighting=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
if [[ ! -d $syntaxhighlighting ]]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $syntaxhighlighting
fi

source ~/.zshrc
