#!/bin/bash

# Brew core packages

# load functions
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

if [[ $(isinstalled brew) -eq 1 ]]; then
    brew install -q gmp isl mpfr libmpc lz4 xz bzip2 zlib zstd binutils m4 pkgconf openssl@3 readline libxcrypt sqlite
else
    echo "Brew is not installed"
fi
