#!/bin/zsh

# zzz
# put mac to sleep
# https://github.com/Orc/Zzz

appname=Zzz
cliname=zzz
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    # zzz does not have a version option
    # verinf $cliname "$appname"
fi