#!/bin/bash

# zsh
# Zsh is an extended Bourne shell with many improvements,
# including some features of Bash, ksh, and tcsh.
# https://www.zsh.org/

export GHCONFDIR=$HOME/GitHub/config
export CONFDIR=$HOME/.config

# symbolic link
makeconfln zsh
lnf $GHCONFDIR/zsh/.zshenv $HOME/.zshenv

# fallback for bash's shopt
if [[ ! "$(osname)" == "macos" ]]; then
    sudo ln -sf ~/GitHub/bin/common/shopt /usr/bin/shopt
fi

# install zsh
if [[ $(isinstalled zsh) -eq 0 ]]; then
    if [[ "$(osname)" != "macos" ]]; then
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        aptinstall zsh
    fi
fi

verinfo zsh

printhead 'Setting zsh as default shell...'
# set default shell
if [[ "$(echo $SHELL | grep -o 'zsh')" != "zsh" ]]; then
    sudo sed -i 's/required/sufficient/g' /etc/pam.d/chsh
    sudo chsh -s $(which zsh) $(whoami)
    sudo sed -i 's/sufficient/required/g' /etc/pam.d/chsh
fi

