#!/bin/bash

# ImageMagick (magick)
# collection of tools to modify and manipulate images
# https://imagemagick.org

if [[ "$(isinstalled magick)" == "no" ]]; then
    brew install -q imagemagick
else
    magick --version | grep "Version"
fi