#!/bin/bash

if [[ "$(osname)" != "macos" ]]; then
    if [[ "$(isinstalled getfacl)" == "no" ]]; then
        # brew install -q acl
        aptinstall acl
    else
        getfacl --version
    fi
else
    echo "Linux is required for this software."
fi
