#!/bin/zsh

# remote files
enm="Environment variables"
enf="https://raw.githubusercontent.com/barabasz/config/main/zsh/.zvars"
lbm="Functions library"
lbf="https://raw.githubusercontent.com/barabasz/lib/main/_all.sh"
lxm="Linux functions"
lxf="https://raw.githubusercontent.com/barabasz/lib/main/_linux.sh"
ghd="https://raw.githubusercontent.com/barabasz/bin/main/install"
# messages
msg_title="Base system components installation"
msg_warn="This script will install base system components."
msg_ok="Core installation completed."
msg_reload="Reload terminal to apply changes."

# main loading function
function source_remote_lib() {
    local url=$1 name=$2 file_content=""
    file_content=$(wget -q -O - $url)
    [[ $? -ne 0 ]] && { echo "Error getting $name ($url)."; return 1; }
    source /dev/stdin <<< "$file_content"
    [[ $? -ne 0 ]] && { echo "Error sourcing $name."; return 1; }
    echo "$name successfully loaded."
}
alias srl="source_remote_lib"
alias sr="source_remote"

srl $enf "$enm" || exit 1    # loading environment variables
srl $lbf "$lbm" || exit 1    # loading functions library
srl $lxf "$lxm" || exit 1    # loading Linux functions

printtitle "$msg_title"      # script title
log::warn "$msg_warn"        # warning message
prompt_continue || exit 0    # prompt to continue

sr $ghd/install-sudo         # sudo if not installed (Debian)
sudo echo > /dev/null        # force sudo password prompt
needrestart-quiet            # disable NEEDRESTART prompt (Ubuntu)
sr $ghd/install-dirs         # creating base directories
sr $ghd/install-locales      # generate locale (Ubuntu/Debian)

sysupdate                    # update and upgrade

sr $ghd/install-git          # Git
sr $ghd/install-repos        # main public repositories
sr $ghd/install-symlinks     # symlinks
sr $ghd/install-zsh          # zsh  

# from here on, scripts are available in the PATH

install-brew                 # Homebrew
install-certs                # Certificates
install-brew-core            # Basic brew libraries
install-ncurses              # Text-based UI library
install-gcc                  # GNU compiler collection
install-cmake                # Cross-platform make
install-acl                  # POSIX access control lists (Linux only)
install-util-linux           # Brew linux utilities (Mac only)
install-gzip                 # gzip
install-7zip                 # 7zip
install-omz                  # oh-my-zsh
install-omp                  # oh-my-posh
install-curl                 # curl
install-bc                   # bc
install-tmux                 # tmux
install-gh                   # GitHub CLI
install-repos-priv           # private repositories

# post-installation tasks

minimize-login-info          # disable login info
set-warsaw-timezone          # setting timezone (Warsaw)
remove-snap                  # remove snap (Ubuntu)

log::ok $msg_ok              # success message
log::info $msg_reload        # reload message
exec zsh                     # attempt to auto-reload shell

