#!/bin/bash

# gzip
# Popular GNU data compression program
# https://www.gnu.org/software/gzip/

appname=gzip
cliname=$appname
pkgname=$appname

if [[ ! $(isinstalled $cliname) ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi

# 7zip
# file archiver with a high compression ratio
# https://7-zip.org

appname=7-zip
cliname=7zz
pkgname=sevenzip
vercmmd="i"

if [[ ! $(isinstalled $cliname) ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname" "$vercmmd"
fi

