#!/bin/zsh

# mc (Midnight Commander)
# feature rich full-screen text mode visual file manager
# https://midnight-commander.org/

cliname='mc'
brewname='midnight-commander'
aptname='mc'
appname='Midnight Commander'
dirname='mc'

installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"
makeconfln $dirname

