#!/bin/zsh

# load variables and functions
zlf=$ZSH_LOAD_FILE; err="$0: unable to load ZSH_LOAD_FILE"
[[ -f $zlf ]] && source $zlf || { printf "$err\n";  exit 1 }

export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_EMOJI=1
export NONINTERACTIVE=1

# Execute shellenv
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if [[ $(isinstalled brew) -eq 0 ]]; then
    # Ubuntu/Debian fix
    if [[ "$(osname)" != "macos" ]]; then
        sudo mkdir -p /home/linuxbrew/
        sudo chmod 755 /home/linuxbrew/
    fi

    # Brew (unattended installation)
    b="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    /bin/bash -c "$(curl -fsSL $b)"

    # Disable analytics
    brew analytics off
else
    verinfo brew
fi




