#!/bin/bash

# yazi
# terminal file manager written in Rust
# https://github.com/sxyazi/yazi

appname=yazi
cliname=$appnamem
dirname=$cliname
pkgname=$cliname

if [[ ! $(isinstalled $cliname) ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q $pkgname
    else
        aptinstall $cliname
    fi
else
    verinf $cliname "$appname"
fi

makeconfln $dirname