#!/bin/zsh

# Oh My Posh
# A prompt theme engine for any shell
# https://ohmyposh.dev
# https://github.com/JanDeDobbeleer/oh-my-posh

# load variables and functions
zlf=$ZSH_LOAD_FILE; err="$0: unable to load ZSH_LOAD_FILE"
[[ -f $zlf ]] && source $zlf || { printf "$err\n";  exit 1 }

appname='Oh My Posh'
cliname=oh-my-posh
dirname=omp
iscript='https://ohmyposh.dev/install.sh'

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    [[ ! -d ~/bin ]] && mkdir ~/bin
    curl -s $iscript | bash -s -- -d ~/bin
    verinfo $cliname "$appname"
fi

makeconfln $dirname

verinfo $cliname "$appname"

