#!/bin/zsh

# acl (POSIX Access Control Lists)
# acl are used to define more fine-grained discretionary access rights
# https://manpages.ubuntu.com/manpages/trusty/man5/acl.5.html

if [[ "$(osname)" != "macos" ]]; then
    appname='Access Control Lists'
    cliname='getfacl'
    brewname=null
    aptname='acl'

    printhead "Installing $appname..."
    installapp $cliname $brewname $aptname "$appname"
    verinfo $cliname "$appname"
fi
