#!/bin/bash

luaver="5.4"

if [[ ! $(isinstalled lua) ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q lua luarocks luv luajit luacheck
    else
        aptinstall lua$luaver
    fi
else
    verinfo lua "Lua" -v
fi
