#!/bin/zsh

# Lynx
# console web browser
# https://www.lynxcloud.app/

appname='Lynx Web Browser'
cliname=lynx
dirname=$cliname
pkgname=$cliname

if [[ ! $(isinstalled $cliname) ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi