#!/bin/zsh

# zzz
# put mac to sleep
# https://github.com/Orc/Zzz

appname=Zzz
cliname=zzz
dirname=$appname
pkgname=$appname

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    brew install -q $pkgname
else
    # zzz does not have a version option
    # verinfo $cliname "$appname"
fi