#!/bin/zsh

# espanso
# A Privacy-first, Cross-platform Text Expander
# https://espanso.org

if [[ $(isinstalled espanso) -eq 0 ]]; then
    brew install espanso
else
    verinfo espanso
fi

lnf $GHCONFPRIVDIR/espanso ~/Library/Application\ Support/espanso
