#!/bin/zsh

# git
# distributed version control system
# https://git-scm.com

appname=git
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ ! $(isinstalled $cliname) ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        xcode-select --install
    else
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        aptinstall $pkgname
    fi
fi

if [[ -z "$(git config --global user.email)" ]]; then
    git config --global user.email "abarabasz@gmail.com"
    git config --global user.name "Andrzej Barabasz"
    git config --global core.pager bat
    git config --global core.editor code
fi

verinfo $cliname "$appname"