#!/bin/bash

# gcc
# GNU compiler collection
# https://gcc.gnu.org/

# load functions
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

if [[ ! $(isinstalled gcc) ]]; then
    brew install -q gcc
else
    gcc --version | grep version
fi