#!/bin/zsh

# yazi
# terminal file manager written in Rust
# https://github.com/sxyazi/yazi

appname=yazi
cliname=$appnamem
dirname=$cliname
pkgname=$cliname

printhead "Installing $appname..."

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q $pkgname
    else
        aptinstall $cliname
    fi
else
    verinfo $cliname "$appname"
fi

makeconfln $dirname

# Plugins

# https://github.com/yazi-rs/plugins/tree/main/mount.yazi
ya pack -a yazi-rs/plugins:mount

# https://github.com/yazi-rs/plugins/tree/main/full-border.yazi
ya pack -a yazi-rs/plugins:full-border

# https://github.com/yazi-rs/plugins/tree/main/git.yazi
ya pack -a yazi-rs/plugins:git

# https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
ya pack -a yazi-rs/plugins:smart-enter

# https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
ya pack -a yazi-rs/plugins:smart-filter

# https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi
ya pack -a yazi-rs/plugins:mime-ext

# Theme

# Dracula: https://draculatheme.com/yazi
git clone https://github.com/dracula/yazi.git ~/.config/yazi/flavors/dracula.yazi