#!/bin/zsh

appname=ACL
cliname=getfacl
pkgname=$appname

if [[ "$(osname)" != "macos" ]]; then
    if [[ $(isinstalled $cliname) -eq 0 ]]; then
        printhead "Installing $appname..."
        aptinstall acl
    else
        verinfo $cliname
    fi
else
    printe "Linux is required for $appname software."
    exit 1
fi
