#!/bin/bash

# THIS SCRIPT IS INTENTIONALLY WRITTEN IN BASH

# load functions
#echo 'Loading install environment and functions...'
#functions="https://raw.githubusercontent.com/barabasz/config/main/zsh/.zsh_functions"
#source <(curl -fsSL $functions)

if [[ "$(osname)" == "ubuntu" ]]; then
    sudo apt install -yq locales > /dev/null 2>&1
    locale=$(locale -a | tr '[:upper:]' '[:lower:]' | grep pl_pl.utf8)
    [[ $locale != "pl_pl.utf8" ]] && sudo locale-gen pl_PL.UTF-8 | grep 'done' || echo "Locale pl_PL.UTF-8 already exists."
    locale=$(locale -a | tr '[:upper:]' '[:lower:]' | grep en_us.utf8)
    [[ $locale != "en_us.utf8" ]] && sudo locale-gen en_US.UTF-8 | grep 'done' || echo "Locale en_US.UTF-8 already exists."
    sudo update-locale
else
    echo "Unsupported OS: $(osname)"
    exit 1
fi
