#!/bin/zsh

# load variables and functions
zlf=$ZSH_LOAD_FILE; err="$0: unable to load ZSH_LOAD_FILE"
[[ -f $zlf ]] && source $zlf || { printf "$err\n";  exit 1 }

# Common scripts
[[ -d $BINDIR ]] && mkdir -p $BINDIR
lns "$GHBINDIR/common" "$BINDIR/common"
lns "$GHBINDIR/install" "$BINDIR/install"
lns "$GHBINDIR/test" "$BINDIR/test"

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    lns "$GHBINDIR/macos" "$BINDIR/thisos"
else
    lns "$GHBINDIR/linux" "$HOME/thisos"
fi

# Library
lns "$GHBINDIR" "$LIBDIR"

# zsh
lns "$GHCONFDIR/zsh" "$ZDOTDIR"
lns "$GHCONFDIR/zsh/.zshenv" "$HOME/.zshenv"

# bash fallback
lns "$GHCONFDIR/bash/.bashrc" "$HOME/.bashrc"
lns "$GHCONFDIR/bash/.bash_profile" "$HOME/.bash_profile"
