#!/bin/bash

# Collection of Linux utilities
# util-linux is keg-only, which means it was not symlinked
# into /opt/homebrew, because macOS provides the uuid.h header.

# binaries location
# /opt/homebrew/opt/util-linux/bin

if [[ "$(isinstalledbybrew util-linux)" == "no" ]]; then
    brew install -q util-linux
else
    brew info util-linux | grep files
fi
