#!/bin/zsh

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat

appname='bat'
cliname='bat'
brewname='bat'
aptname='bat'
dirname='bat'

installapp $cliname $brewname $aptname $appname
makeconfln $dirname