#!/bin/zsh

# Oh My Posh
# A prompt theme engine for any shell
# https://ohmyposh.dev
# https://github.com/JanDeDobbeleer/oh-my-posh

appname='Oh My Posh'
cliname=oh-my-posh
dirname=omp
iscript='https://ohmyposh.dev/install.sh'

printhead 'Installing Oh My Posh..'

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    [[ ! -d ~/bin ]] && mkdir ~/bin
    curl -s $iscript | bash -s -- -d ~/bin
else
    $cliname upgrade --force
fi

lns "$GHCONFDIR/$dirname" "$CONFDIR/$dirname" 
verinfo $cliname "$appname"

