#!/bin/zsh

# Common scripts
[[ -d $BINDIR ]] && mkdir -p $BINDIR
lnf $GHBINDIR/common $BINDIR/common
lnf $GHBINDIR/install $BINDIR/install
lnf $GHBINDIR/test $BINDIR/test

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    lnf $GHBINDIR/macos $BINDIR/thisos
else
    lnf $GHBINDIR/linux $HOME/thisos
fi

# Library
lnf $GHBINDIR/lib $LIBDIR

# zsh
lnf $GHCONFDIR/zsh $ZDOTDIR
lnf $GHCONFDIR/zsh/.zshenv $HOME/.zshenv

# bash fallback
lnf $GHCONFDIR/bash/.bashrc $HOME/.bashrc
lnf $GHCONFDIR/bash/.bash_profile $HOME/.bash_profile
