#!/bin/zsh

# zsh
# Zsh is an extended Bourne shell with many improvements,
# including some features of Bash, ksh, and tcsh.
# https://www.zsh.org/

# directory variables
export ZDOTDIR=$HOME/.config/zsh
export GHCONFDIR=$HOME/GitHub/config
export CONFDIR=$HOME/.config

# zsh symbolic links
lns "$GHCONFDIR/zsh" "$ZDOTDIR"
lns "$GHCONFDIR/zsh/.zshenv" "$HOME/.zshenv"

appname='zsh shell'
cliname='zsh'
brewname='zsh'
aptname='zsh'

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"

printhead 'Setting zsh as default shell...'
set_default_shell zsh
