#!/bin/bash

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat

appname=bat
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname" "-V"
fi

makeconfln $dirname