#!/bin/zsh

# gcc
# GNU compiler collection
# https://gcc.gnu.org/

# load functions
scrpath="https://raw.githubusercontent.com/barabasz/resources/main/install.sh"
source /dev/stdin <<< "$(curl -fsSL $scrpath)"

if [[ $(isinstalled gcc) -eq 0 ]]; then
    brew install -q gcc
else
    gcc --version | grep version
fi