#!/bin/zsh

# zoxide
# smarter cd command, inspired by z and autojump
# https://github.com/ajeetdsouza/zoxide

appname=zoxide
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname"
fi

makeconfln $dirname