#!/bin/zsh

# nvim (neovim)
# hyperextensible Vim-based text editor
# https://neovim.io/

appname="Neovim"
cliname=nvim
brewname=nvim
aptname=null
verswitch="--version"

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"

# Default editor in Debian-based systems
if [[ ! "$(osname)" == "macos" ]]; then
    sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/nvim 1000
fi

# Configuration files
mkdir -p ~/.config/nvim
lns "$GHCONFDIR/nvim" "$CONFDIR/nvim"

# Plugin manager
target_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/paqs/start/paq-nvim
if [[ ! -d "$target_dir" ]]; then
    git clone --depth=1 https://github.com/savq/paq-nvim.git "$target_dir"
else
    log::info "$(ansi reset)Repository paq-nvim.git already exists at $target_dir"
fi