#!/bin/zsh

# calc
# C-style arbitrary precision calculator with custom functions
# http://www.isthe.com/chongo/tech/comp/calc/

if [[ $(isinstalled calc) -eq 0 ]]; then
    brew install -q calc
else
    calc -v
fi