#!/bin/zsh

# read su password
sudo printf ''

# mc (Midnight Commander)
# feature rich full-screen text mode visual file manager
# https://midnight-commander.org/
printhead 'Installing mc...'
install-mc

# nnn
# Tiny, lightning fast, feature-packed file manager
# https://github.com/jarun/nnn
printhead 'Installing nnn...'
install-nnn

# fd
# fd is a program to find entries in your filesystem
# https://github.com/sharkdp/fd
printhead 'Installing fd...'
install-fd

# fzf
# Command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf
printhead 'Installing fzf...'
install-fzf

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat
printhead 'Installing bat...'
install-bat

# htop
# Improved top (interactive process viewer)
# https://htop.dev/
printhead 'Installing htop...'
install-htop

# nvim (neovim)
# hyperextensible Vim-based text editor
# https://neovim.io/
printhead 'Installing nvim...'
install-nvim

# navi
# Interactive cheatsheet tool for the command-line
# https://github.com/denisidoro/navi
printhead 'Installing navi...'
install-navi

# tlrc
# tlrc is a tldr client written in Rust
# https://github.com/tldr-pages/tlrc
printhead 'Installing tldr...'
install-tldr

# wget
# Internet file retriever
# https://www.gnu.org/software/wget/
printhead 'Installing wget...'
install-wget

# The Fuck
# Programmatically correct mistyped console commands
# https://github.com/nvbn/thefuck
printhead 'Installing thefuck...'
install-thefuck

# Lynx
# console web browser
# https://www.lynxcloud.app/
printhead 'Installing lynx...'
install-lynx

# calc
# C-style arbitrary precision calculator with custom functions
# http://www.isthe.com/chongo/tech/comp/calc/
printhead 'Installing calc...'
install-calc

# zzz
# put mac to sleep
# https://github.com/Orc/Zzz
if [[ "$(osname)" == "macos" ]]; then
    printhead 'Installing zzz...'
    install-zzz
fi

# eza
# modern alternative for the ls
# https://github.com/eza-community/eza
printhead 'Installing eza...'
install-eza

# ripgrep
# line-oriented search tool for files
# https://github.com/BurntSushi/ripgrep
printhead 'Installing ripgrep...'
install-ripgrep

# zoxide
# smarter cd command, inspired by z and autojump
# https://github.com/ajeetdsouza/zoxide
printhead 'Installing zoxide...'
install-zoxide

install-lsd

install-rmlint

printinfo 'Shell apps installation completed.'
