#!/bin/bash

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat

appname=bat
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ "$(isinstalled $cliname)" == "no" ]]; then
    brew install -q $pkgname
else
    verinf $cliname "$appname" "-V"
fi

makeconfln $dirname