#!/bin/zsh

printhead "Re-cloning all repos"...

log::info "This will erase all existing repositories in ~/GitHub and clone them again."
prompt_continue || exit 0

if [[ "$(gh auth status 2>/dev/null | grep -o 'Logged')" != "Logged" ]]; then
    log::error "You are not logged in to GitHub CLI. Please log in first."
    log::info "You can do this by running $(ansi bold)gh auth login$(ansi reset)."
    exit 1
fi

mkdir -p ~/GitHub && cd $_
repos=("bin" "config" "lib" "confpriv" "scripts" "resources") && i=0
for repo in "${repos[@]}"; do
    rm -rf $repo
    log::info "Cloning $repo..."
    gh repo clone "barabasz/$repo"
    log::info "$repo successfully cloned."
    ((i++))
done
log::ok "Successfully cloned $i repositories."