#!/bin/zsh

repos=($(git-repos))
[[ -z $repos ]] && { printe "No repositories found."; return 1; }
count=$(echo $repos | wc -w | tr -d ' ')
printhead "Checking status for $count repositories."

i=1
for repo in $(git-repos)
do
    printhead "$i/$count $(basename $repo)"
    cd $repo
    printc $(git remote get-url origin)
    git status
    ((i++))
done
