#!/bin/zsh

repos=($(git-repos))
[[ -z $repos ]] && { printe "No repositories found."; return 1; }
count=$(echo $repos | wc -w | tr -d ' ')
printhead "Pushing $count repositories to the remote."

i=1
for repo in $(git-repos)
do
    printhead "$i/$count $(basename $repo)"
    cd $repo
    printc $(git remote get-url origin)
    git add --all
    git commit -m "update"
    git push
    ((i++))
done


