#!/bin/bash

# load functions
test -f ~/.zshenv && source "$_"
if [ -z "${ZDOTDIR}" ]; then
    source $ZDOTDIR/.zsh_functions
else
    source <(curl -fsSL https://raw.githubusercontent.com/barabasz/resources/main/install.sh)
fi

if [[ "$(osname)" == "ubuntu" ]]; then
    sudo chmod -x /etc/update-motd.d/00-header
    sudo chmod -x /etc/update-motd.d/10-help-text
    sudo chmod -x /etc/update-motd.d/50-motd-news
    sudo chmod -x /etc/update-motd.d/90-updates-available
    sudo chmod -x /etc/update-motd.d/91-contract-ua-esm-status
fi

if [[ "$(osname)" == "debian" ]]; then
    sudo chmod -x /etc/update-motd.d/10-uname
fi

if [[ ! "$(osname)" == "macos" ]]; then
    sudo ln -sf ~/GitHub/config/motd/05-header /etc/update-motd.d
fi
