#!/bin/bash

if [[ "$(osname)" == "ubuntu" ]]; then
    sudo chmod -x /etc/update-motd.d/00-header
    sudo chmod -x /etc/update-motd.d/10-help-text
    sudo chmod -x /etc/update-motd.d/50-motd-news
    sudo chmod -x /etc/update-motd.d/90-updates-available
    sudo chmod -x /etc/update-motd.d/91-contract-ua-esm-status
else

if [[ "$(osname)" == "debian" ]]; then
    sudo chmod -x /etc/update-motd.d/10-uname
else

ln -sf ~/GitHub/config/motd/05-header /etc/update-motd.d

