#!/bin/bash

envopt="NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive"
aptopt="-qq"
filter1='^Hit|^Get'
filter2='^NEEDRESTART|^update|Reading'

sudo apt-get update | grep -Ev $filter1
sudo $envopt apt-get $aptopt upgrade | grep -Ev $filter2
sudo $envopt apt-get $aptopt dist-upgrade

sudo apt-get $aptopt clean
sudo apt-get $aptopt autoclean
sudo apt-get $aptopt autoremove
sudo sync
