#!/bin/zsh

# remove snap

printhead 'Removing snap...'

if [[ $(isinstalled snap) -eq 1 ]]; then
    sudo snap remove --purge lxd
    sudo snap remove --purge core20
    sudo snap remove --purge snapd
    sudo apt-get -qq remove --purge --autoremove snapd
    log::ok "Snap removed."
else
    log::info "Snap not installed."
fi
