#!/bin/bash

# load functions
source ~/.zsh_functions

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

if [[ "$(osname)" == "ubuntu" ]]; then
    aptinstall language-pack-pl-base language-pack-pl

    sudo localectl set-locale LANG=en_US.UTF-8
    sudo localectl set-locale LANGUAGE=en_US:en:C
    sudo localectl set-locale LC_MESSAGES=en_US.UTF-8

    sudo localectl set-locale LC_ADDRESS=en_US.UTF-8
    sudo localectl set-locale LC_COLLATE=pl_PL.UTF-8
    sudo localectl set-locale LC_CTYPE=pl_PL.UTF-8
    sudo localectl set-locale LC_IDENTIFICATION=pl_PL.UTF-8
    sudo localectl set-locale LC_MEASUREMENT=pl_PL.UTF-8
    sudo localectl set-locale LC_MONETARY=pl_PL.UTF-8
    sudo localectl set-locale LC_MONETARY=pl_PL.UTF-8
    sudo localectl set-locale LC_NAME=en_US.UTF-8
    sudo localectl set-locale LC_NUMERIC=pl_PL.UTF-8
    sudo localectl set-locale LC_PAPER=pl_PL.UTF-8
    sudo localectl set-locale LC_TELEPHONE=en_US.UTF-8
    sudo localectl set-locale LC_TIME=pl_PL.UTF-8
fi


