#!/bin/bash

# load functions
source ~/.zsh_functions

# temporary locales
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

if [[ "$(locale -a | awk '{print tolower($0)}' | grep -o 'pl_pl.utf')" != "pl_pl.utf" ]]; then
    # Debian
    if [[ "$(osname)" == "debian" ]]; then
        sudo sed -i -e 's/# pl_PL.UTF-8 UTF-8/pl_PL.UTF-8 UTF-8/' /etc/locale.gen
        sudo dpkg-reconfigure --frontend=noninteractive locales
    fi
    # Ubuntu
    if [[ "$(osname)" == "ubuntu" ]]; then
        aptinstall language-pack-pl-base language-pack-pl
        sudo locale-gen pl_PL.UTF-8
    fi
else
    echo "Already installed: $(locale -a | grep 'pl')"
fi

sudo localectl set-locale LANG=en_US.UTF-8
sudo localectl set-locale LANGUAGE=en_US:en:C
sudo localectl set-locale LC_MESSAGES=en_US.UTF-8

sudo localectl set-locale LC_ADDRESS=pl_PL.UTF-8
sudo localectl set-locale LC_COLLATE=pl_PL.UTF-8
sudo localectl set-locale LC_CTYPE=pl_PL.UTF-8
sudo localectl set-locale LC_IDENTIFICATION=pl_PL.UTF-8
sudo localectl set-locale LC_MEASUREMENT=pl_PL.UTF-8
sudo localectl set-locale LC_MONETARY=pl_PL.UTF-8
sudo localectl set-locale LC_NAME=pl_PL.UTF-8
sudo localectl set-locale LC_NUMERIC=pl_PL.UTF-8
sudo localectl set-locale LC_PAPER=pl_PL.UTF-8
sudo localectl set-locale LC_TELEPHONE=pl_PL.UTF-8
sudo localectl set-locale LC_TIME=pl_PL.UTF-8

# Setting timezone
if [[ "$(cat /etc/timezone | grep -o 'Warsaw')" != "Warsaw" ]]; then
    sudo timedatectl set-timezone Europe/Warsaw
    sudo dpkg-reconfigure -f noninteractive tzdata
else
    echo "Timezone: $(cat /etc/timezone)"
fi