#!/bin/zsh

if [[ "$(cat /etc/timezone | grep -o 'Warsaw')" != "Warsaw" ]]; then
    sudo timedatectl set-timezone Europe/Warsaw
    sudo dpkg-reconfigure -f noninteractive tzdata
else
    echo "Timezone: $(cat /etc/timezone)"
fi